# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.IntegerField(verbose_name='A cada ')),
                ('period', models.DateTimeField(auto_now_add=True, verbose_name='Agendado em')),
            ],
            options={
                'verbose_name_plural': 'Histórico de agendamento',
                'verbose_name': 'Agendamento da dieta',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.CharField(max_length=500, verbose_name='Conteudo')),
                ('period', models.DateTimeField(auto_now=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name_plural': 'Histórico de cadastro de alertas',
                'verbose_name': 'Cadastro de alertas',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('period', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
            ],
            options={
                'verbose_name_plural': 'Coletas do reservatório',
                'verbose_name': 'Reservatório',
                'ordering': ['period'],
            },
        ),
    ]
