# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.IntegerField(verbose_name='A cada ')),
                ('slug', models.SlugField(verbose_name='Identificador')),
                ('period', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
            ],
            options={
                'ordering': ['period'],
                'verbose_name': 'Agendamento da dieta',
                'verbose_name_plural': 'Histórico de agendamento',
            },
        ),
        migrations.CreateModel(
            name='Reservatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('slug', models.SlugField(verbose_name='Identificador')),
                ('period', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
            ],
            options={
                'ordering': ['period'],
                'verbose_name': 'Reservatório',
                'verbose_name_plural': 'Coletas do reservatório',
            },
        ),
    ]
