# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo'),
        ),
    ]
